### ISSUE TITLE
High cpu usage in idle

### ISSUE THREAD

**Issue by alexwall** [jbaron/cats#144]
Hi, 

cats (node) have cpu usage of 5-15% in idle 
I use this version 838666634ebbdd5268e1cad267413d0033a6ae26

**Comment by jbaron** [comment]
If I remember correctly there are one of two calls to the TyepeScript
language servicces that are not yet conditional (so they happen regardless
if code has changed or not). This could be optimized and should reduce load
while the IDE is idle.

If you see the heartbeat moving (at the status bar in the bottom of the
screen), there is something going on in the background. The main thread is
invoking the webworker for some language service call.

-- Peter

**Comment by alexwall** [comment]
Ok the "heartbeat" is not moving, it's pure idle mode

**Comment by jbaron** [comment]
Did some more checking and my findings:

1) If no project is loaded at all, the cpu usage is close to 0%. So this is expected behaviour.

2) If a project is loaded (but no editor is opened yet), the cpu usage indeed goes up (for me a bit less than 5% average, but I guess depends on things like CPU, type of hardest etc). The only background activity that is now going on is the fs.watch on the open project directories in order to determine if someone is adding or deleting a file. 

BTW, right now CATS doesn’t release the directory watcher once a user closed the tree of that directory in the navigation tab. This could still be optimized.

3) If also file editors are opened, the cpu increases a bit more, but still stays below 10%, This could be further decreased by smarter dealing with changes and less often call the worker thread.


So it seems the fs.watch (at least on OS X) takes more CPU that one would expect to check a few directories.


— Peter
