### ISSUE TITLE
Qooxdoo release 5.0.2

### ISSUE THREAD

**Issue by tcsaddul** [jbaron/cats#162]
Hello!  Can you update your qooxdoo release? Thanks

**Comment by tcsaddul** [comment]
Any update on this? I can donate 300usd for this update.

**Comment by jbaron** [comment]
I just updated to QX 5.0.2 and TypeScript 2.4.2 (free of charge :). One issue is with the shortcuts due to some change between 5.0 and 5.0.2 on the command class. But other then that it should work fine (tested only limited myself). 

However since previous version was already based on 5.0, not many QX changes that I can see. Any particular reason for wanting 5.0.2?

**Comment by jbaron** [comment]
Fixed also the shortcuts. So should work all as before but now using Qooxdoo 5.0.2

**Comment by tcsaddul** [comment]
Thanks a lot for this update!  Tested it flawlessly working with my application.  With regards to my donation, I'm **very serious** about it because I have used your library in the applications that we sell to our customers.  I know you have invested a lot of effort in this project.  I can only send through western union, please email me recipient name at tcsaddul@yahoo.com

**Comment by jbaron** [comment]
Thanks for the offer, much appreciated. But this is just my contribution to the community. I already used so much open source software throughout my life, this is the least I can do.

**Comment by tcsaddul** [comment]
I will not insist.  I know you are a brilliant programmer and earn a lot from your talent.  Thank you very much for this contribution.
